### ISSUE TITLE
Can you add the results about ShareGPT4Video-8B on VideoHallucer benchmark?

### ISSUE THREAD

**Issue by xiaoachen98** [patrick-tssn/VideoHallucer#2]
Thanks for your awesome work of building a solid benchmark for video hallucinations. I wonder if you could add the results of ShareGPT4Video-8B on your benchmark. We provide the inference code [here](https://github.com/ShareGPT4Omni/ShareGPT4Video), very easy to follow. Many thanks!

**Comment by patrick-tssn** [comment]
Thank you for your work. I have updated your models to our benchmark. For further evaluation, you are encouraged to make a PR or submit your results to me (flagwyx@gmail.com).

**Comment by xiaoachen98** [comment]
> Thank you for your work. I have updated your models to our benchmark. For further evaluation, you are encouraged to make a PR or submit your results to me ([flagwyx@gmail.com](mailto:flagwyx@gmail.com)).

Thanks for your reply! It seems like we should make some efforts to alleviate hallucinations for ShareGPT4Video-8B~
